### ISSUE TITLE
Maxent_Optimization issue

### ISSUE THREAD

**Issue by sandimas** [josefkaufmann/ana_cont#11]
Line 701 in solvers.py has an error. I believe it should read

`result_dict.update({"probability": prob})
`

**Comment by josefkaufmann** [comment]
Hi @sandimas, thank you for the precise feedback! This was indeed a bug, I just fixed it. 

Please consider however that I cannot recommend using the "classic" variant of Maxent. The "chi2kink" variant usually performs better.
