### ISSUE TITLE
Scipy.integrate simps needs to be changed to simpson

### ISSUE THREAD

**Issue by AlzbetaKadlecova** [josefkaufmann/ana_cont#14]
Dear developer, following the recommended installation path I upgraded my python libraries (they currently update to PyQt5-Qt5-5.15.14 PyQt5-sip-12.15.0 cython-3.0.10 h5py-3.11.0 matplotlib-3.9.1 pyqt5-5.15.11 scipy-1.14.0 wheel-0.43.0), installed the code via pip and ran it in a Jupyter notebook. 
I got a 'module scipy.integrate doesn't have an attribute simps' error - full error message in attachement. 
The fix seems to be to change 'simps' to 'simpson'.
![anacont_error](https://github.com/user-attachments/assets/ae9cd40c-c647-40a9-ab76-f51ecd8e0bae)

**Comment by josefkaufmann** [comment]
Dear Alzbeta, I apologize for the late response. In [this commit](https://github.com/josefkaufmann/ana_cont/commit/1aa9e62cde34c59b785a117462c028740329811b) I fixed the issue, the updated version is also available on PyPI, such that after `pip install -U ana_cont` it should be possible to run ana_cont with newer versions of scipy. 
Best regards,
JK

**Comment by AlzbetaKadlecova** [comment]
Thank you so much! Best regards, AK
