### ISSUE TITLE
simplify inputs?

### ISSUE THREAD

**Issue by dombrno** [josefkaufmann/ana_cont#2]
I would like to suggest the following possibility: offer the user the option to not supply the AnalyticContinuationProblem constructor with data for the ```im_axis``` parameter. In case this parameter is not supplied, the AnalyticContinuationProblem would build it in the most straightforward way, using
* the length the ```im_data``` array for the number n of imaginary frequencies
* the parameter ```kernel_mode``` to determine if these frequencies are bosonic or fermionic
* the parameter ```beta```
and assuming that the data correspond to the first n positive Matsubara frequencies. 

I think it would simplify further the inputs, and would correspond to most of the use cases?

**Comment by josefkaufmann** [comment]
Thank you for this suggestion! The next version should contain a wrapper that simplifies the usage of ana_cont by setting certain reasonable default values and checking the input for some common pitfalls. Your suggestions will be implemented there.

**Comment by josefkaufmann** [comment]
In the current version of the master branch, there is a function continue_maxent in the module continuation.
It sets as many fields as possible automatically, but most of them can be overridden. 
Use it with caution, since it has a complicated program flow and was not yet tested for all cases.

**Comment by josefkaufmann** [comment]
Very late comment: The continue_maxent function mentioned above is now deprecated. Instead, there is now a graphical user interface which fulfills the purpose of input simplification in a much better way. The respective scripts are scripts/maxent.py, scripts/maxent_bosonic.py and scripts/pade.py
